Drum Machine: Timer Class Reference
Timer Class Reference
Call a callback function in a given interval, determining the time with a given precision. Higher precision means higher demand in resources.
#include <Timer.h>
Public Member Functions
Timer (unsigned int interval, unsigned int precision)
template<typename Function , typename... Args>
void start (Function &&callback, Args &&... args)
void stop ()
unsigned int getInterval () const
void setInterval (unsigned int interval)
Private Member Functions
long long getCurrentTimeMillis ()
Private Attributes
unsigned int precision
The precision in nanoseconds.
unsigned int interval
The interval in milliseconds.
bool running
Is the timer currently running.
Detailed Description
Call a callback function in a given interval, determining the time with a given precision. Higher precision means higher demand in resources.
Definition at line 17 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Timer::Timer (unsigned int interval, unsigned int precision)
Constructor
Parameters
interval the interval in milliseconds in which the callback function is called.
precision the precision in nanoseconds with which to determine the current time. Higher precision means higher demand in resources.
Definition at line 5 of file Timer.cpp.
Member Function Documentation
getCurrentTimeMillis()
long long Timer::getCurrentTimeMillis () inline private
< Helper function to get the current time in milliseconds
Definition at line 23 of file Timer.h.
getInterval()
unsigned int Timer::getInterval () const
Returns
the interval with which the timer calls the callback function.
Definition at line 11 of file Timer.cpp.
References interval.
setInterval()
void Timer::setInterval (unsigned int interval)
Parameters
interval the interval with which the timer calls the callback function.
Definition at line 15 of file Timer.cpp.
References interval.
Referenced by DrumMachine::setBPM(), and DrumMachine::startLoop().
start()
template<typename Function , typename... Args> void Timer::start (Function && callback, Args &&... args) inline
Starts the timer.
Parameters
callback the callback function the timer calls in the determined interval.
args arguments to pass to the callback function upon call.
Definition at line 42 of file Timer.h.
Referenced by DrumMachine::startLoop(), and RaspInputController::startPolling().
stop()
void Timer::stop ()
Stops the timer
Definition at line 7 of file Timer.cpp.
References running.
Referenced by RaspInputController::stop(), and DrumMachine::stopLoop().
Member Data Documentation
interval
unsigned int Timer::interval private
The interval in milliseconds.
Definition at line 20 of file Timer.h.
Referenced by getInterval(), and setInterval().
precision
unsigned int Timer::precision private
The precision in nanoseconds.
Definition at line 19 of file Timer.h.
running
bool Timer::running private
Is the timer currently running.
Definition at line 21 of file Timer.h.
Referenced by stop().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp