Drum Machine: DrumMachine Class Reference
DrumMachine Class Reference
Handles the beat loop and samples including correct timing for the give BPM, playing them at the correct beat steps and increasing and decreasing the volume.
#include <DrumMachine.h>
Public Member Functions
DrumMachine (AOutputController &outputController)
void startLoop ()
void stopLoop ()
void addSample (Sample)
void increaseVolume (float value)
void increaseActiveSampleVolume (float value)
void increaseBpm (unsigned short value)
void toggleSampleAtBeat (unsigned short beat)
bool isLoopRunning ()
void setBPM (unsigned short bpm)
unsigned short getBPM ()
void setMasterVolume (float volume)
float getMasterVolume ()
void setActiveSample (unsigned short newActiveSample)
unsigned short getActiveSample ()
Private Member Functions
void allocateChannels ()
Helper function which allocates the audio channels.
void openAudio ()
Initializes the audio.
Private Attributes
const unsigned short MIN_BPM = 20
The lowest value the bpm can be.
const unsigned short MAX_BPM = 220
The highest value the bpm can be.
const unsigned short WHOLE_BEATS = 4
The number of whole beats the loop has.
const unsigned short BEATS_PER_WHOLE_BEAT = 4
The number of beats one whole beat has.
const unsigned short TOTAL_BEATS = WHOLE_BEATS * BEATS_PER_WHOLE_BEAT
The resulting total beats the loop has.
const unsigned long LOOP_PRECISION_NANOS = 10000
The precision with which the loop timer runs.
unsigned short bpm
BPM at which the loop runs.
unsigned short currentBeat
The number of the current beat.
unsigned short activeSample
The index of the active sample.
unsigned int beatMillis
Milliseconds that one beat lasts.
bool loopRunning
Stores whether the loop is running or not.
float volume
The current master volume.
AOutputController & outputController
Reference to the regsitered OutputController.
Timer loop
The loop timer.
vector< Sample > samples
A List of all added samples.
Detailed Description
Handles the beat loop and samples including correct timing for the give BPM, playing them at the correct beat steps and increasing and decreasing the volume.
Definition at line 29 of file DrumMachine.h.
Constructor & Destructor Documentation
DrumMachine()
DrumMachine::DrumMachine (AOutputController & outputController) explicit
Constructor
Parameters
outputController the outputController the drum machine passes events to
Definition at line 10 of file DrumMachine.cpp.
References allocateChannels(), and openAudio().
Member Function Documentation
addSample()
void DrumMachine::addSample (Sample sample)
Add a sample to be available for use in the drum machine. The order of adding samples determines the buttons they are mapped to
Definition at line 122 of file DrumMachine.cpp.
References samples, Sample::setMasterVolume(), and volume.
Referenced by setup().
allocateChannels()
void DrumMachine::allocateChannels () private
Helper function which allocates the audio channels.
Definition at line 29 of file DrumMachine.cpp.
Referenced by DrumMachine().
getActiveSample()
unsigned short DrumMachine::getActiveSample ()
Returns
The number of the currently active sample
Definition at line 166 of file DrumMachine.cpp.
References activeSample.
Referenced by DrumMachineInputListener::inputEvent().
getBPM()
unsigned short DrumMachine::getBPM ()
Returns
the current BPM
Definition at line 101 of file DrumMachine.cpp.
References bpm.
Referenced by increaseActiveSampleVolume(), increaseBpm(), DrumMachineInputListener::inputEvent(), and setActiveSample().
getMasterVolume()
float DrumMachine::getMasterVolume ()
Returns
the current master volume
Definition at line 118 of file DrumMachine.cpp.
References volume.
Referenced by DrumMachineInputListener::inputEvent().
increaseActiveSampleVolume()
void DrumMachine::increaseActiveSampleVolume (float value)
Increases the volume of the currently active sample by a given value.
Parameters
value value to increase the active sample volume by
Definition at line 77 of file DrumMachine.cpp.
References activeSample, getBPM(), outputController, samples, and AOutputController::showSampleScreen().
Referenced by DrumMachineInputListener::inputEvent().
increaseBpm()
void DrumMachine::increaseBpm (unsigned short value)
Increases the BPM by a given value.
Parameters
value value to increase the bpm by
Definition at line 170 of file DrumMachine.cpp.
References getBPM(), and setBPM().
Referenced by DrumMachineInputListener::inputEvent().
increaseVolume()
void DrumMachine::increaseVolume (float value)
Increases the volume by a given value.
Parameters
value value to increase the master volume by
Definition at line 67 of file DrumMachine.cpp.
References setMasterVolume(), and volume.
isLoopRunning()
bool DrumMachine::isLoopRunning ()
Returns
whether the loop is currently running
Definition at line 127 of file DrumMachine.cpp.
References loopRunning.
Referenced by DrumMachineInputListener::inputEvent().
openAudio()
void DrumMachine::openAudio () private
Initializes the audio.
Definition at line 19 of file DrumMachine.cpp.
Referenced by DrumMachine().
setActiveSample()
void DrumMachine::setActiveSample (unsigned short newActiveSample)
Sets the active sample
Parameters
newActiveSample The number of the new active sample
Definition at line 131 of file DrumMachine.cpp.
References activeSample, AOutputController::activeSampleChange(), getBPM(), sample::NO_SAMPLE, outputController, AOutputController::playPositionChange(), samples, AOutputController::showMainScreen(), and AOutputController::showSampleScreen().
Referenced by DrumMachineInputListener::inputEvent().
setBPM()
void DrumMachine::setBPM (unsigned short bpm)
Sets the BPM to a specific value
Parameters
bpm the new bpm value
Definition at line 89 of file DrumMachine.cpp.
References beatMillis, BEATS_PER_WHOLE_BEAT, bpm, loop, MAX_BPM, MIN_BPM, outputController, AOutputController::setBeatDuration(), Timer::setInterval(), and AOutputController::showMainScreen().
Referenced by increaseBpm(), and setup().
setMasterVolume()
void DrumMachine::setMasterVolume (float volume)
Sets the master volume to a specific value
Parameters
volume the new master volume
Definition at line 105 of file DrumMachine.cpp.
References samples, and volume.
Referenced by increaseVolume().
startLoop()
void DrumMachine::startLoop ()
Starts the beat loop.
Definition at line 37 of file DrumMachine.cpp.
References beatMillis, currentBeat, loop, loopRunning, outputController, AOutputController::positionChange(), samples, Timer::setInterval(), Timer::start(), and TOTAL_BEATS.
Referenced by DrumMachineInputListener::inputEvent().
stopLoop()
void DrumMachine::stopLoop ()
Stops the beat loop.
Definition at line 61 of file DrumMachine.cpp.
References currentBeat, loop, loopRunning, and Timer::stop().
Referenced by DrumMachineInputListener::inputEvent().
toggleSampleAtBeat()
void DrumMachine::toggleSampleAtBeat (unsigned short beat)
Toggles whether the current sample is played at a specific beat
Parameters
beat the beat the sample should be toggled at
Definition at line 152 of file DrumMachine.cpp.
References activeSample, sample::NO_SAMPLE, outputController, AOutputController::playPositionChange(), and samples.
Referenced by DrumMachineInputListener::inputEvent().
Member Data Documentation
activeSample
unsigned short DrumMachine::activeSample private
The index of the active sample.
Definition at line 40 of file DrumMachine.h.
Referenced by getActiveSample(), increaseActiveSampleVolume(), setActiveSample(), and toggleSampleAtBeat().
beatMillis
unsigned int DrumMachine::beatMillis private
Milliseconds that one beat lasts.
Definition at line 41 of file DrumMachine.h.
Referenced by setBPM(), and startLoop().
BEATS_PER_WHOLE_BEAT
const unsigned short DrumMachine::BEATS_PER_WHOLE_BEAT = 4 private
The number of beats one whole beat has.
Definition at line 34 of file DrumMachine.h.
Referenced by setBPM().
bpm
unsigned short DrumMachine::bpm private
BPM at which the loop runs.
Definition at line 38 of file DrumMachine.h.
Referenced by getBPM(), and setBPM().
currentBeat
unsigned short DrumMachine::currentBeat private
The number of the current beat.
Definition at line 39 of file DrumMachine.h.
Referenced by startLoop(), and stopLoop().
loop
Timer DrumMachine::loop private
The loop timer.
Definition at line 46 of file DrumMachine.h.
Referenced by setBPM(), startLoop(), and stopLoop().
LOOP_PRECISION_NANOS
const unsigned long DrumMachine::LOOP_PRECISION_NANOS = 10000 private
The precision with which the loop timer runs.
Definition at line 36 of file DrumMachine.h.
loopRunning
bool DrumMachine::loopRunning private
Stores whether the loop is running or not.
Definition at line 42 of file DrumMachine.h.
Referenced by isLoopRunning(), startLoop(), and stopLoop().
MAX_BPM
const unsigned short DrumMachine::MAX_BPM = 220 private
The highest value the bpm can be.
Definition at line 32 of file DrumMachine.h.
Referenced by setBPM().
MIN_BPM
const unsigned short DrumMachine::MIN_BPM = 20 private
The lowest value the bpm can be.
Definition at line 31 of file DrumMachine.h.
Referenced by setBPM().
outputController
AOutputController& DrumMachine::outputController private
Reference to the regsitered OutputController.
Definition at line 45 of file DrumMachine.h.
Referenced by increaseActiveSampleVolume(), setActiveSample(), setBPM(), startLoop(), and toggleSampleAtBeat().
samples
vector<Sample> DrumMachine::samples private
A List of all added samples.
Definition at line 47 of file DrumMachine.h.
Referenced by addSample(), increaseActiveSampleVolume(), setActiveSample(), setMasterVolume(), startLoop(), and toggleSampleAtBeat().
TOTAL_BEATS
const unsigned short DrumMachine::TOTAL_BEATS = WHOLE_BEATS * BEATS_PER_WHOLE_BEAT private
The resulting total beats the loop has.
Definition at line 35 of file DrumMachine.h.
Referenced by startLoop().
volume
float DrumMachine::volume private
The current master volume.
Definition at line 43 of file DrumMachine.h.
Referenced by addSample(), getMasterVolume(), increaseVolume(), and setMasterVolume().
WHOLE_BEATS
const unsigned short DrumMachine::WHOLE_BEATS = 4 private
The number of whole beats the loop has.
Definition at line 33 of file DrumMachine.h.
The documentation for this class was generated from the following files:
DrumMachine.h
DrumMachine.cpp