Drum Machine: DrumMachineInputListener Class Reference
DrumMachineInputListener Class Reference
InputListener implementation for the drum machine to handle input events.
#include <DrumMachineInputListener.h>
Public Member Functions
DrumMachineInputListener (DrumMachine &drumMachine)
void inputEvent (unsigned short event) override
Private Attributes
const float VOLUME_STEP_SIZE = 0.05f
Value to increase the volume in one step.
const unsigned short BPM_STEP_SIZE = 1
Value to increase the bpm in one step.
DrumMachine & drumMachine
Reference to the drum machine thats used by the listener.
Detailed Description
InputListener implementation for the drum machine to handle input events.
Definition at line 11 of file DrumMachineInputListener.h.
Constructor & Destructor Documentation
DrumMachineInputListener()
DrumMachineInputListener::DrumMachineInputListener (DrumMachine & drumMachine) explicit
Constructor
Parameters
drumMachine the drum machine to be used by the listener
Definition at line 8 of file DrumMachineInputListener.cpp.
Member Function Documentation
inputEvent()
void DrumMachineInputListener::inputEvent (unsigned short input) override virtual
Called when new input events are detected
Parameters
input the input that was detected.
Implements InputListener.
Definition at line 10 of file DrumMachineInputListener.cpp.
References beat::BEAT1, beat::BEAT10, inputs::BEAT10_BUTTON, beat::BEAT11, inputs::BEAT11_BUTTON, beat::BEAT12, inputs::BEAT12_BUTTON, beat::BEAT13, inputs::BEAT13_BUTTON, beat::BEAT14, inputs::BEAT14_BUTTON, beat::BEAT15, inputs::BEAT15_BUTTON, beat::BEAT16, inputs::BEAT16_BUTTON, inputs::BEAT1_BUTTON, beat::BEAT2, inputs::BEAT2_BUTTON, beat::BEAT3, inputs::BEAT3_BUTTON, beat::BEAT4, inputs::BEAT4_BUTTON, beat::BEAT5, inputs::BEAT5_BUTTON, beat::BEAT6, inputs::BEAT6_BUTTON, beat::BEAT7, inputs::BEAT7_BUTTON, beat::BEAT8, inputs::BEAT8_BUTTON, beat::BEAT9, inputs::BEAT9_BUTTON, BPM_STEP_SIZE, drumMachine, DrumMachine::getActiveSample(), DrumMachine::getBPM(), DrumMachine::getMasterVolume(), DrumMachine::increaseActiveSampleVolume(), DrumMachine::increaseBpm(), DrumMachine::isLoopRunning(), sample::NO_SAMPLE, sample::SAMPLE1, inputs::SAMPLE1_BUTTON, sample::SAMPLE2, inputs::SAMPLE2_BUTTON, sample::SAMPLE3, inputs::SAMPLE3_BUTTON, sample::SAMPLE4, inputs::SAMPLE4_BUTTON, sample::SAMPLE5, inputs::SAMPLE5_BUTTON, sample::SAMPLE6, inputs::SAMPLE6_BUTTON, sample::SAMPLE7, inputs::SAMPLE7_BUTTON, sample::SAMPLE8, inputs::SAMPLE8_BUTTON, DrumMachine::setActiveSample(), inputs::START_STOP_BUTTON, DrumMachine::startLoop(), DrumMachine::stopLoop(), DrumMachine::toggleSampleAtBeat(), inputs::VOLUME_BPM_DOWN_BUTTON, inputs::VOLUME_BPM_UP_BUTTON, and VOLUME_STEP_SIZE.
Member Data Documentation
BPM_STEP_SIZE
const unsigned short DrumMachineInputListener::BPM_STEP_SIZE = 1 private
Value to increase the bpm in one step.
Definition at line 14 of file DrumMachineInputListener.h.
Referenced by inputEvent().
drumMachine
DrumMachine& DrumMachineInputListener::drumMachine private
Reference to the drum machine thats used by the listener.
Definition at line 16 of file DrumMachineInputListener.h.
Referenced by inputEvent().
VOLUME_STEP_SIZE
const float DrumMachineInputListener::VOLUME_STEP_SIZE = 0.05f private
Value to increase the volume in one step.
Definition at line 13 of file DrumMachineInputListener.h.
Referenced by inputEvent().
The documentation for this class was generated from the following files:
DrumMachineInputListener.h
DrumMachineInputListener.cpp